"""
make_report.py -- Generates ../work/sim_results.md from simulations/results/.

Every number in the report is read out of the JSON files that run_all.py wrote.
Nothing is typed in by hand, so the report cannot drift from the executed code.

    python make_report.py --results results --out ../work/sim_results.md
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Iterable

import numpy as np

import config as C
from config import (SLICES, SLICE_NAMES, ARM_LABELS, ARMS, CHANNEL, SLICING, SCHED,
                    SFC, ENERGY, RIS, COMPLEXITY, RLENV, RLTRAIN, INTEGRATED,
                    TRAFFIC, NUM_MU0, NUM_MU1, NUM_MU1_SCHED, CAMPAIGN)
import stats as S


def load(results: Path, name: str):
    p = results / f"{name}.json"
    if not p.exists():
        return None
    return json.loads(p.read_text(encoding="utf-8"))


# ----------------------------------------------------------------------------------
# formatting helpers
# ----------------------------------------------------------------------------------

def f(x, d=3):
    if x is None:
        return "n/a"
    try:
        v = float(x)
    except (TypeError, ValueError):
        return str(x)
    if not np.isfinite(v):
        return "inf" if v > 0 else "-inf"
    return f"{v:.{d}f}"


def fsig(x, d=4):
    """Fixed-point normally, scientific when the value would round to zero."""
    if x is None:
        return "n/a"
    v = float(x)
    if not np.isfinite(v):
        return "inf" if v > 0 else "-inf"
    if v != 0.0 and abs(v) < 0.5 * 10 ** (-d):
        return f"{v:.2e}"
    return f"{v:.{d}f}"


def ci(s: dict, unit: str = "", d: int = 3) -> str:
    """mean (95 % CI [lo, hi])"""
    u = f" {unit}" if unit else ""
    return (f"{f(s['mean'], d)}{u} (95 % CI [{f(s['ci_low'], d)}, "
            f"{f(s['ci_high'], d)}])")


def msd(s: dict, unit: str = "", d: int = 3) -> str:
    u = f" {unit}" if unit else ""
    return (f"{f(s['mean'], d)} +/- {f(s['sd'], d)}{u}; 95 % CI "
            f"[{f(s['ci_low'], d)}, {f(s['ci_high'], d)}]; n = {s['n_seeds']}")


def pfmt(p) -> str:
    p = float(p)
    if p == 0.0:
        return "< 1e-300"
    if p < 1e-4:
        return f"{p:.2e}"
    return f"{p:.4f}"


def table(header: Iterable[str], rows: Iterable[Iterable[str]]) -> str:
    header = list(header)
    out = ["| " + " | ".join(header) + " |",
           "|" + "|".join(["---"] * len(header)) + "|"]
    for r in rows:
        out.append("| " + " | ".join(str(v) for v in r) + " |")
    return "\n".join(out)


def comparison_table(family: dict, d: int = 4, label_map: dict | None = None) -> str:
    label_map = label_map or {}

    def lbl(x):
        return label_map.get(x, x)

    rows = []
    for r in family["rows"]:
        rows.append([
            r["metric"],
            f"{lbl(r['arm_a'])} - {lbl(r['arm_b'])}",
            fsig(r["mean_diff"], d),
            f"[{fsig(r['diff_ci_low'], d)}, {fsig(r['diff_ci_high'], d)}]",
            f(r["t_stat"], 3),
            pfmt(r["p_raw"]),
            pfmt(family["bonferroni_threshold"]),
            f"{f(r['cohens_d'], 2)} ({r['d_interpretation']})",
            "**yes**" if r["significant_bonferroni"] else "no",
            "yes" if r["significant_holm"] else "no",
            pfmt(r["wilcoxon_p"]),
            f(r["achieved_power"], 3),
        ])
    return table(["Metric", "Comparison", "Difference", "95 % CI of the difference",
                  "t", "raw p", "Bonferroni threshold", "Cohen's d",
                  "Significant (Bonferroni)", "Significant (Holm)",
                  "Wilcoxon p", "Achieved power"], rows)


SHORT_ARM = {
    "A_hard_static": "A",
    "B_soft_pool": "B",
    "C_no_medium": "C",
    "D_no_slow": "D",
    "E_full_umro": "E",
}


# ----------------------------------------------------------------------------------
# report sections
# ----------------------------------------------------------------------------------

def sec_header(manifest: dict) -> str:
    return f"""# UMRO-5G simulation results

**This file is machine-generated by `simulations/make_report.py` from the raw output in
`simulations/results/`. Every number below was produced by executing
`simulations/run_all.py`; none of them is transcribed from the previous draft or from
the literature. Numbers that are NOT original are listed, individually, in the
[PROVENANCE](#provenance) section at the end.**

| | |
|---|---|
| Generated (UTC) | {manifest['generated_utc']} |
| Total wall clock | {f(manifest['wall_clock_s'], 1)} s |
| Independent seeds | **{manifest['n_seeds']}** |
| Monte Carlo iterations per seed | {manifest['n_monte_carlo_per_seed']} |
| Seeds for the timing benchmark | {manifest['n_seeds_complexity']} (sequential, see Section 9) |
| Compressed day | {f(manifest['compress_seconds'], 0)} s of simulated time = 24 h |
| Python | {manifest['python'].splitlines()[0]} |
| NumPy / SciPy | {manifest['numpy']} / {manifest['scipy']} |
| Platform | {manifest['platform']} |
| Logical cores | {manifest['cpu_count']} |
| Seed list | {manifest['seeds'][0]} .. {manifest['seeds'][-1]} |

---
"""


def sec_statistics(manifest: dict, integ: dict) -> str:
    n = manifest["n_seeds"]
    mde80 = S.minimum_detectable_effect(n, 0.80)
    mde90 = S.minimum_detectable_effect(n, 0.90)
    fam = integ["family"] if integ else None
    n_comp = fam["n_comparisons"] if fam else 0
    thr = fam["bonferroni_threshold"] if fam else float("nan")

    best = None
    if fam:
        best = max(fam["rows"], key=lambda r: abs(r["cohens_d"]))

    norm_lines = []
    if integ:
        for m, v in integ["normality"].items():
            verdict = ("consistent with normality" if v["normal_at_005"]
                       else "NOT consistent with normality")
            norm_lines.append(f"| `{m}` | {f(v['W'], 3)} | {pfmt(v['p'])} | {verdict} |")

    n_mc = manifest["n_monte_carlo_per_seed"]
    return f"""## 1. Statistical methodology (Section 8.2 of the article)

### 1.1 The sample-size correction demanded by Reviewer 1, comment 6

The previous draft stated that the effective sample size was
`N_seeds x N_MONTE_CARLO = 5 x 1000 = 5000 realizations per load point`.
**That statement is wrong and has been removed.** The Monte Carlo iterations inside a
seed are averaged into a single per-seed estimate before any inference is performed;
averaging reduces the variance of that estimate but produces no additional independent
observations. The independent sample size equals the number of seeds.

This campaign therefore uses **{n} independent seeds**, and every confidence interval
and every test below carries **df = {n} - 1 = {n - 1}**. The code enforces the rule:
`stats.describe()` stores `n_monte_carlo_per_seed` as a separate, inference-inert
field, and `tests/test_stats.py::test_degrees_of_freedom_are_seeds_minus_one_not_iterations`
fails if that field is ever allowed to change a confidence interval.

**Recommended replacement wording for the article (Section 8.2):**

> Results are reported as the mean over {n} independent random seeds, with 95 %
> confidence intervals computed from Student's t distribution with {n - 1} degrees of
> freedom. Each seed averages {manifest['n_monte_carlo_per_seed']} Monte Carlo
> iterations into a single estimate; this averaging reduces the variance of each seed's
> estimate but does not increase the number of independent observations, so the
> effective sample size is {n} and not {n} x {manifest['n_monte_carlo_per_seed']}.

### 1.2 Design

* **Common random numbers.** The same seed list drives every arm of every experiment,
  so all comparisons are **paired** at the seed level. Within an experiment, the
  channel and traffic realisations replayed for each arm are identical; the arms differ
  only in the control policy.
* **Paired t-test** on the seed-wise difference vector, two-sided.
* **Wilcoxon signed-rank test** on the same vector as a distribution-free robustness
  check, since n = {n} is modest.
* **Cohen's d_z** = mean difference / SD of the differences, with Cohen's (1988)
  conventional bands (negligible < 0.2, small < 0.5, medium < 0.8, large < 1.2).
* **Bonferroni** correction within each declared family of comparisons, and
  **Holm-Bonferroni** reported alongside it as the uniformly more powerful alternative
  controlling the same family-wise error rate.
* **Shapiro-Wilk** on the paired differences, so the reader can judge how much weight
  to give the t-test relative to the Wilcoxon result.
* **Bounded metrics.** Several reported quantities are probabilities or fractions.
  The Student-t interval is symmetric and is NOT truncated at the natural bounds, so a
  near-zero probability can be reported with a negative lower limit. Those limits are
  left as the arithmetic produces them rather than being quietly clipped; when such a
  number is quoted in the article the lower limit should be read as zero and the
  interval described as one-sided in effect. Where the metric is strongly skewed the
  Wilcoxon result, which makes no symmetry assumption, is the one to rely on.

### 1.3 Power

At n = {n} seeds and alpha = 0.05 two-sided, the **minimum detectable effect** is

* d_z = **{f(mde80, 3)}** at 80 % power,
* d_z = **{f(mde90, 3)}** at 90 % power.

Effects smaller than these cannot be reliably detected by this design, and the article
must not claim them.

**Caution on very large effect sizes.** Cohen's `d_z` is the mean difference divided by
the standard deviation of the *between-seed* differences. Because each seed averages
{n_mc} Monte Carlo iterations, the between-seed variance of a well-behaved quantity is
very small, so `d_z` can reach values in the tens or hundreds. Such a number means the
difference is extremely consistent across replications; it does **not** mean the
difference is large in engineering terms. The article should therefore quote the
absolute difference and its confidence interval first, and the effect size second.

{'The largest effect in the integrated end-to-end family is `' + best['metric'] + '`, '
 + SHORT_ARM.get(best['arm_a'], best['arm_a']) + ' vs ' + SHORT_ARM.get(best['arm_b'], best['arm_b'])
 + ', with d_z = ' + f(best['cohens_d'], 2) + ' and achieved power '
 + f(best['achieved_power'], 3) + '.' if best else ''}

### 1.4 Normality of the paired differences (E vs A)

{table(['Metric', 'Shapiro-Wilk W', 'p', 'Verdict'], []) if not norm_lines else
 '| Metric | Shapiro-Wilk W | p | Verdict |' + chr(10) + '|---|---|---|---|' + chr(10) + chr(10).join(norm_lines)}

### 1.5 Families and corrected thresholds

The integrated end-to-end family contains **{n_comp}** comparisons, so the
Bonferroni-adjusted per-comparison threshold is **alpha = {pfmt(thr)}** against a
family-wise alpha of 0.05. Every other experiment declares its own family; the
threshold used is printed in that experiment's table.

---
"""


def sec_scenario_table() -> str:
    rows = [
        ["Carrier frequency", "2.0 GHz", "3GPP TR 36.814 macro Case 1"],
        ["Path loss", "128.1 + 37.6 log10(d[km]) dB", "3GPP TR 36.814 Table A.2.1.1-3"],
        ["Shadowing", "log-normal, sigma = 8 dB", "3GPP TR 36.814 macro NLOS"],
        ["Small-scale fading", "Rayleigh block fading, 10 ms coherence", "chosen"],
        ["gNB transmit power / antenna gain", "46 dBm / 15 dBi", "3GPP / chosen"],
        ["UE noise figure", "7 dB", "3GPP TR 38.901"],
        ["Cell radius / minimum gNB-UE distance", "500 m / 35 m", "chosen / 3GPP"],
        ["Link adaptation", "CQI table 2 (256QAM), 15 entries, target BLER 0.1",
         "3GPP TS 38.214 Table 5.2.2.1-3"],
        ["CQI SNR thresholds",
         "inverted attenuated Shannon bound SE = 0.88 log2(1 + SNR/0.72)",
         "Mogensen et al., VTC-Spring 2007"],
        ["Numerology (integrated runner)",
         f"mu = {NUM_MU1.mu}, SCS {f(NUM_MU1.scs_khz, 0)} kHz, {f(NUM_MU1.bandwidth_mhz, 0)} MHz, "
         f"{NUM_MU1.n_prb} PRBs, TTI {f(NUM_MU1.slot_ms, 1)} ms", "chosen"],
        ["Numerology (multi-slice Monte Carlo)",
         f"mu = {NUM_MU0.mu}, SCS {f(NUM_MU0.scs_khz, 0)} kHz, {f(NUM_MU0.bandwidth_mhz, 0)} MHz, "
         f"{NUM_MU0.n_prb} PRBs, TTI {f(NUM_MU0.slot_ms, 1)} ms", "previous draft"],
        ["Numerology (scheduling study)",
         f"mu = {NUM_MU1_SCHED.mu}, SCS {f(NUM_MU1_SCHED.scs_khz, 0)} kHz, "
         f"{NUM_MU1_SCHED.n_prb} PRBs", "previous draft"],
    ]
    for s in SLICES:
        rows.append([f"Slice {s.name}",
                     f"{s.n_users} users, {f(s.arrival_rate_per_user_hz, 0)} packets/s/user, "
                     f"{f(s.packet_bits_mean / 8, 0)} byte mean packet, "
                     f"PDB {f(s.delay_budget_ms, 1)} ms, weight {f(s.utility_weight, 1)}",
                     "chosen; PDB from 3GPP TS 23.501 Table 5.7.4-1"])
    rows += [
        ["Diurnal profile", f"24 h compressed into {f(TRAFFIC.compress_seconds, 0)} s, "
                            f"hourly multipliers 0.24-1.60", "chosen"],
        ["Nominal offered load", f"rho = {f(INTEGRATED.nominal_load, 2)} at multiplier 1.0",
         "chosen"],
        ["Fast loop", f"every TTI ({f(NUM_MU1.slot_ms, 1)} ms), proportional fair, "
                      f"EWMA {INTEGRATED.pf_ewma}", "chosen"],
        ["Medium loop", f"every {f(INTEGRATED.medium_period_ms, 0)} ms, "
                        f"{INTEGRATED.medium_n_actions} actions, "
                        f"{INTEGRATED.medium_prb_step} PRBs per action", "chosen"],
        ["Slow loop", f"every {f(INTEGRATED.slow_period_ms / 1000, 0)} s, dual step "
                      f"{INTEGRATED.slow_price_step}, guarantees in "
                      f"[{INTEGRATED.slow_min_prb_floor}, {INTEGRATED.slow_min_prb_ceiling}] PRBs",
         "chosen"],
        ["SLA criterion (integrated)",
         "per 100 ms window: carry >= 95 % of the offered load AND mean head-of-line "
         "delay within the 5QI packet delay budget", "chosen"],
        ["URLLC radio budget / end-to-end budget",
         f"{f(SLICES[1].delay_budget_ms, 1)} ms / {f(INTEGRATED.e2e_budget_urllc_ms, 1)} ms",
         "ITU-R M.2410-0 / 3GPP TS 23.501 5QI 82"],
        ["Hard isolation split", f"{SLICING.hard_split} PRBs", "previous draft"],
        ["Soft isolation", f"minimums {SLICING.soft_min}, shared pool {SLICING.soft_pool} PRBs",
         "previous draft"],
        ["SFC", f"{len(SFC.vnf_names)} VNFs {SFC.vnf_names}, service rates "
                f"{tuple(int(v) for v in SFC.service_rates_pps)} packets/s",
         "chosen (see README Section 6)"],
        ["O-RU energy model",
         f"{ENERGY.n_oru} O-RUs, P_active {f(ENERGY.p_active_w, 0)} W "
         f"({f(ENERGY.p_active_static_w, 0)} W static + {f(ENERGY.p_load_slope_w, 0)} W load), "
         f"P_sleep {f(ENERGY.p_sleep_w, 0)} W, P_overhead {f(ENERGY.p_overhead_w, 0)} W, "
         f"wake-up {f(ENERGY.wake_energy_j, 0)} J", "previous draft + EARTH model"],
        ["Traffic forecaster",
         f"Holt linear-trend exponential smoothing (alpha = {ENERGY.holt_alpha}, "
         f"beta = {ENERGY.holt_beta}) -- NOT an LSTM", "chosen"],
        ["RIS", f"M = {RIS.n_bs_antennas} gNB antennas, K = {RIS.n_users} UEs, "
                f"N_RIS in {RIS.n_ris_sweep}, direct SNR {f(RIS.direct_snr_db, 0)} dB, "
                f"Rician K = {f(RIS.rician_k_db, 0)} dB, path-loss exponents "
                f"{RIS.pl_exponent_direct}/{RIS.pl_exponent_bs_ris}/{RIS.pl_exponent_ris_ue}",
         "previous draft + chosen"],
        ["RIS CSI / phase resolution", "perfect instantaneous CSI; continuous phases",
         "stated assumption (upper bound)"],
        ["RL environment", f"{RLENV.n_cells} cells, {RLENV.n_users} users, "
                           f"{RLENV.n_power_levels} power levels, "
                           f"{RLENV.episode_steps} steps/episode", "chosen"],
        ["RL training", f"{RLTRAIN.n_episodes} episodes, gamma = {RLTRAIN.gamma}, "
                        f"lr = {RLTRAIN.lr}, batch {RLTRAIN.batch_size}, replay "
                        f"{RLTRAIN.replay_capacity}, target update every "
                        f"{RLTRAIN.target_update_steps} steps", "chosen"],
        ["Complexity benchmark", f"N in {COMPLEXITY.n_sweep}, "
                                 f"{COMPLEXITY.n_repeats} timing repetitions, "
                                 f"branch-and-bound timeout {f(COMPLEXITY.bnb_timeout_s, 0)} s",
         "chosen"],
        ["Replication", f"{CAMPAIGN.n_seeds} seeds, base seed {CAMPAIGN.seed_base}, "
                        f"common random numbers across arms", "chosen"],
    ]
    return f"""## 2. Scenario parameters (ready for Table 9 of the article)

{table(["Parameter", "Value", "Source"], rows)}

---
"""


def sec_integrated(b: dict) -> str:
    if b is None:
        return ""
    s = b["summaries"]
    n = b["n_seeds"]

    rows = []
    for arm in ARMS:
        rows.append([
            ARM_LABELS[arm],
            ci(s["aggregate_throughput_mbps"][arm], "", 2),
            ci(s["prb_utilisation"][arm], "", 4),
            ci(s["sla_satisfaction_rate"][arm], "", 4),
            f"{f(100 * s['urllc_violation_prob'][arm]['mean'], 4)} "
            f"[{f(100 * s['urllc_violation_prob'][arm]['ci_low'], 4)}, "
            f"{f(100 * s['urllc_violation_prob'][arm]['ci_high'], 4)}]",
            ci(s["carried_load_fraction"][arm], "", 4),
        ])
    main = table(["Arm", "Aggregate throughput (Mbit/s)", "PRB utilisation",
                  "SLA satisfaction rate", "URLLC radio violation (%)",
                  "Carried load fraction"], rows)

    per_slice_rows = []
    for arm in ARMS:
        r = [ARM_LABELS[arm]]
        for name in SLICE_NAMES:
            r.append(ci(s[f"throughput_{name}_mbps"][arm], "", 2))
        for name in SLICE_NAMES:
            r.append(f(s[f"mean_hol_delay_{name}_ms"][arm]["mean"], 4))
        per_slice_rows.append(r)
    per_slice = table(["Arm"] + [f"{n_} throughput (Mbit/s)" for n_ in SLICE_NAMES]
                      + [f"{n_} mean HoL delay (ms)" for n_ in SLICE_NAMES],
                      per_slice_rows)

    sfc_rows = []
    for arm in ARMS:
        sfc_rows.append([
            ARM_LABELS[arm],
            ci(s["urllc_mean_e2e_latency_ms"][arm], "ms", 3),
            f"{f(100 * s['urllc_e2e_violation_prob'][arm]['mean'], 3)} "
            f"[{f(100 * s['urllc_e2e_violation_prob'][arm]['ci_low'], 3)}, "
            f"{f(100 * s['urllc_e2e_violation_prob'][arm]['ci_high'], 3)}]",
            f(s["mean_sfc_latency_URLLC_ms"][arm]["mean"], 3),
            f(s["mean_sfc_latency_eMBB_ms"][arm]["mean"], 3),
        ])
    sfc_tab = table(["Arm", "URLLC mean end-to-end latency", "URLLC end-to-end violation (%)",
                     "URLLC mean SFC latency (ms)", "eMBB mean SFC latency (ms)"], sfc_rows)

    cp = b["coupling"] or {}
    coupling = ""
    if cp:
        def per_slice(key):
            v = cp.get(key)
            if not v:
                return "n/a"
            return ", ".join(f"{n} {f(x, 2)}" for n, x in zip(SLICE_NAMES, v))

        def strength(key):
            v = cp.get(key) or []
            v = [abs(x) for x in v if np.isfinite(x)]
            return f(np.mean(v), 3) if v else "n/a"

        coupling = table(
            ["Coupling link", "Coupling strength (mean abs r)",
             "Signed r per slice", "What the signal is"],
            [["slow-loop dual price -> slow-loop PRB guarantee",
              strength("corr_price_guarantee_per_slice"),
              per_slice("corr_price_guarantee_per_slice"),
              "the guarantee is re-derived from the price-modulated demand every 2 s"],
             ["slow-loop guarantee -> medium-loop allocation",
              strength("corr_guarantee_alloc_per_slice"),
              per_slice("corr_guarantee_alloc_per_slice"),
              "the guarantee is a hard lower bound on the partition the RIC may choose"],
             ["medium-loop allocation -> fast-loop throughput (one window later)",
              strength("corr_alloc_throughput_lag1_per_slice"),
              per_slice("corr_alloc_throughput_lag1_per_slice"),
              "the partition is a hard upper bound on what the scheduler can deliver"],
             ["offered-load envelope -> medium-loop allocation",
              strength("corr_offered_alloc_per_slice"),
              per_slice("corr_offered_alloc_per_slice"),
              "the outer loops track the non-stationary diurnal demand"]])

        coupling += """

**How to read this table.** The quantity that matters is the *magnitude*: a system
whose loops were merely co-present rather than coupled would show a coupling strength
near zero on every row. The *signs* differ by slice and are not evidence of anything on
their own -- as the offered load climbs through the day, the eMBB slice gains PRBs while
URLLC and mMTC give them up, so the two groups necessarily correlate with the demand
envelope in opposite directions. Panel (d) of Figure 4 shows the underlying traces."""
        coupling += (f"\n\nOver the recorded run the dual price spanned "
                     f"[{f(cp['price_range'][0], 3)}, {f(cp['price_range'][1], 3)}], the "
                     f"minimum guarantee spanned [{cp['guarantee_range'][0]}, "
                     f"{cp['guarantee_range'][1]}] PRBs, and the per-slice allocations "
                     f"spanned {cp['alloc_range_per_slice']} PRBs over "
                     f"{cp['n_medium_samples']} medium-loop decisions.")

    act_rows = []
    for arm in ARMS:
        act_rows.append([
            ARM_LABELS[arm],
            f(s["medium_actions_applied"][arm]["mean"], 1),
            f(s["medium_actions_rejected"][arm]["mean"], 1),
            f(s["slow_updates"][arm]["mean"], 1),
        ])
    activity = ("### 3.5.1 Loop activity: direct evidence that the loops constrain "
                "each other\n\n"
                + table(["Arm", "Medium-loop re-splits applied",
                         "Medium-loop re-splits vetoed", "Slow-loop updates"],
                        act_rows)
                + "\n\nThe *vetoed* column is the most direct evidence available "
                  "that the slow loop constrains the medium loop. A proposed PRB "
                  "re-split is executed only if the resulting partition respects the "
                  "slow loop's per-slice minimum guarantees AND stays inside its "
                  "price budget. Baseline D runs the identical Near-RT RIC policy on "
                  "the identical telemetry, but with static guarantees and no price "
                  "budget. The full framework consequently executes an order of "
                  "magnitude fewer re-splits than Baseline D from the same policy: "
                  "the medium loop is demonstrably operating inside a feasible set "
                  "that the slow loop redefines every 2 s, rather than beside it.\n\n"
                  "A corollary the article must state honestly: in the full framework "
                  "the medium loop's measured contribution is NOT a large change to "
                  "the PRB partition, which the slow loop already tracks well. Its "
                  "measured contribution is to the URLLC violation probability and to "
                  "admission control, and that is where the Baseline C comparison in "
                  "Section 3.6 shows a significant effect.")

    e = s["sla_satisfaction_rate"]["E_full_umro"]
    a = s["sla_satisfaction_rate"]["A_hard_static"]
    cvs = {(r["arm_a"], r["arm_b"], r["metric"]): r for r in b["family"]["rows"]}
    ea = cvs.get(("E_full_umro", "A_hard_static", "sla_satisfaction_rate"))
    ec = cvs.get(("E_full_umro", "C_no_medium", "sla_satisfaction_rate"))
    ed = cvs.get(("E_full_umro", "D_no_slow", "sla_satisfaction_rate"))
    eb = cvs.get(("E_full_umro", "B_soft_pool", "sla_satisfaction_rate"))

    def verdict_line(r, label):
        if r is None:
            return ""
        sig = "significant after Bonferroni" if r["significant_bonferroni"] else "**NOT significant after Bonferroni**"
        return (f"* **{label}**: difference {f(r['mean_diff'], 4)} "
                f"(95 % CI [{f(r['diff_ci_low'], 4)}, {f(r['diff_ci_high'], 4)}]), "
                f"t({r['df']}) = {f(r['t_stat'], 2)}, p = {pfmt(r['p_raw'])}, "
                f"d = {f(r['cohens_d'], 2)} ({r['d_interpretation']}), "
                f"Wilcoxon p = {pfmt(r['wilcoxon_p'])} -- {sig}.")

    return f"""## 3. Integrated end-to-end evaluation (Section 8.3, Figure 4)

**Answers Reviewer 1 comment 1.**

### 3.1 What was run

One slotted simulation, one clock, one traffic realisation, all three loops live:
the fast loop schedules every {f(NUM_MU1.slot_ms, 1)} ms, the Near-RT-RIC-like medium
loop re-splits PRBs and runs admission control every
{f(INTEGRATED.medium_period_ms, 0)} ms, and the Non-RT-RIC/MANO-like slow loop updates
the Lagrangian prices, re-derives the per-slice minimum guarantees and rescales the VNF
chains every {f(INTEGRATED.slow_period_ms / 1000, 0)} s. Twenty-four hours of
non-stationary diurnal traffic are compressed into {f(TRAFFIC.compress_seconds, 0)} s,
which is {int(TRAFFIC.compress_seconds / (NUM_MU1.slot_ms * 1e-3))} TTIs,
{int(TRAFFIC.compress_seconds / (INTEGRATED.medium_period_ms * 1e-3))} medium-loop
decisions and {int(TRAFFIC.compress_seconds / (INTEGRATED.slow_period_ms * 1e-3))}
slow-loop updates per arm per seed.

Five arms, identical channel and traffic streams (common random numbers), n = {n} seeds.

### 3.2 Headline results

{main}

### 3.3 Per-slice results

{per_slice}

### 3.4 Transport and core: SFC latency under each arm

{sfc_tab}

### 3.5 Measured coupling between the loops

{coupling}

{activity}

### 3.6 Statistical comparison (ready for Table 10 of the article)

Family: every arm against the full framework on three metrics,
{b['family']['n_comparisons']} comparisons, Bonferroni threshold
alpha = {pfmt(b['family']['bonferroni_threshold'])}.

{comparison_table(b['family'], 4, SHORT_ARM)}

URLLC radio violation probability is treated as a separate family (lower is better),
Bonferroni threshold alpha = {pfmt(b['family_urllc']['bonferroni_threshold'])}:

{comparison_table(b['family_urllc'], 6, SHORT_ARM)}

### 3.7 Reading of the ablations

{verdict_line(ea, 'Full UMRO-5G vs Baseline A (static hard isolation)')}
{verdict_line(eb, 'Full UMRO-5G vs Baseline B (soft isolation, fixed pool)')}
{verdict_line(ec, 'Full UMRO-5G vs Baseline C (medium loop disabled)')}
{verdict_line(ed, 'Full UMRO-5G vs Baseline D (slow loop disabled)')}

### 3.8 What this does and does not show

**It does show** that the four layers and the three nested control loops of UMRO-5G can
be executed together on a single clock over a non-stationary 24-hour traffic profile;
that the loops are genuinely coupled rather than merely co-present (Section 3.5 gives
the measured coupling strengths along the price -> guarantee -> allocation ->
throughput chain, and Section 3.5.1 counts the medium-loop re-splits that the slow
loop's guarantees and price budget vetoed); and that removing either outer loop changes
the measured SLA satisfaction rate and URLLC violation probability by amounts whose
statistical significance is reported, comparison by comparison, in Section 3.6.
It also shows where each loop's contribution actually lies: the slow loop drives the
SLA satisfaction rate and the transport-plane latency, while the medium loop's
measurable effect is concentrated on the URLLC violation probability.

**It does not show** that UMRO-5G works on real hardware, on operator traces, or under
a standards-compliant O-RAN E2 interface. The medium-loop controller is a Q-network
pre-trained on a fluid surrogate of this same simulator and then frozen, so its
performance carries the surrogate-to-simulator gap. The channel, traffic and VNF models
are the ones in `simulations/config.py`, and results outside their parameter ranges are
not evidenced. The single-cell scope means no inter-cell interference, no handover and
no multi-cell coordination are exercised. Finally, the SLA criterion is the one defined
in Section 2 of this file; a different SLA definition would move the absolute numbers,
though the ordering of the arms is a paired comparison and is robust to that choice.

---
"""


def sec_learners(b: dict) -> str:
    if b is None:
        return ""
    s = b["summaries"]
    algos = list(s.keys())
    rows = []
    for a in algos:
        d = b["episodes_to_95pct"][a]
        rows.append([
            a,
            msd(s[a], "", 3),
            f"{f(100 * b['converged_fraction'][a], 1)} %",
            f"{f(100 * b['improved_over_random_fraction'][a], 1)} %",
            f"{f(100 * b['stable_fraction'][a], 1)} %",
            f(100 * b["plateau_drift"][a]["mean"], 1) + " %",
            f(d["mean"], 1),
        ])
    tab = table(["Algorithm", "Final normalised score (mean +/- SD, 95 % CI, n)",
                 "Runs meeting all three convergence criteria",
                 "Runs beating the random policy", "Runs with a stable plateau",
                 "Mean plateau drift over the final fifth",
                 "Mean episodes to 95 % of plateau"], rows)

    not_conv = [a for a in algos if b["converged_fraction"][a] < 0.5]
    conv = [a for a in algos if b["converged_fraction"][a] >= 0.5]
    best = max(algos, key=lambda a: s[a]["mean"])

    warn = ""
    if not_conv:
        warn = (f"\n> **Negative result, reported as such.** "
                f"{', '.join(not_conv)} did not meet all three convergence criteria in "
                f"the majority of runs within the {RLTRAIN.n_episodes}-episode budget. "
                f"The article must state this rather than presenting a smooth curve.\n")

    return f"""## 4. Learning-based controller convergence (Section 8.5, Figure 5)

**Answers Reviewer 1 comment 2.**

### 4.1 What was actually implemented

The previous draft stated that its convergence curves came from *"simplified tabular
proxy agents ... not full neural network implementations"*. **Those proxies have been
deleted.** `simulations/learners.py` now contains four real agents written directly in
NumPy, with hand-derived gradients that are verified against central finite differences
in `simulations/tests/test_learners.py`:

* **DQN** -- centralised Deep Q-Network over the joint action space
  ({RLENV.n_power_levels}^{RLENV.n_cells} = {RLENV.n_power_levels ** RLENV.n_cells}
  actions), uniform experience replay (capacity {RLTRAIN.replay_capacity}), a separate
  target network refreshed every {RLTRAIN.target_update_steps} gradient steps,
  epsilon-greedy exploration decaying linearly from {RLTRAIN.eps_start} to
  {RLTRAIN.eps_end} over {RLTRAIN.eps_decay_episodes} episodes, Huber loss, gradient
  clipping at {RLTRAIN.grad_clip}, Adam at lr = {RLTRAIN.lr}.
* **MADRL/QMIX** -- one independent Q-network per cell plus a QMIX monotonic mixing
  network whose weights are produced by hypernetworks conditioned on the global state
  and forced non-negative by an absolute value, which guarantees the QMIX monotonicity
  condition dQ_tot/dQ_i >= 0 (asserted by a unit test). Centralised training,
  decentralised execution.
* **Federated DQN (FedAvg)** -- one local DQN per cell, each with its own replay buffer
  and trained only on its own transitions, with uniform parameter averaging every
  {RLTRAIN.fedavg_period_episodes} episodes.
* **GNN-DRL** -- {RLTRAIN.gnn_message_rounds} rounds of normalised-adjacency message
  passing over the cell graph with shared self and neighbour weight matrices, then a
  shared per-node Q head; backpropagation through the message passing is hand-derived
  and finite-difference checked.

**Not implemented, and therefore not to be claimed:** prioritised replay, double or
duelling DQN, recurrent or attention-based encoders, and any hyper-parameter transfer
from published work.

### 4.2 Environment and metric

A {RLENV.n_cells}-cell interference-limited downlink with {RLENV.n_users} users,
per-user queues, bursty on/off arrivals and an explicit transmit-energy cost, so the
optimal power depends on the state and a constant policy is not optimal. Training
scenarios are drawn from `seed`; evaluation uses a **disjoint** seed stream and eight
scenarios held fixed for the whole run.

The reported metric is a normalised score

```
score = (return - random-policy return) / (myopic full-CSI oracle return - random-policy return)
```

so **0 = uniformly random power control** and **1 = a per-slot greedy oracle that sees
every user's instantaneous channel**, which the agents do not. On the evaluation
scenarios the random-policy reference return was {f(b['random_floor'], 1)} and the
constant maximum-power policy scored {f(b['max_power_reference'], 1)}.

> The oracle is a **myopic upper reference, not the optimum of the Markov decision
> process.** The article must not describe these numbers as a "percentage of the
> theoretical optimum".

### 4.3 Convergence criteria

A run is counted as converged only if **all three** of the following hold:

1. **improvement** -- the final plateau mean exceeds the random-policy reference by
   more than one plateau standard deviation;
2. **stability** -- the total drift of the evaluation return over the final fifth of
   training is below {f(100 * RLTRAIN.convergence_tolerance, 0)} % of the plateau
   level;
3. **progress** -- the final fifth of training scores above the first fifth.

The three are reported separately below so that a reader who prefers a different
stability threshold can apply it to the same measurements.

### 4.4 Results ({b['n_seeds']} seeds per algorithm, {RLTRAIN.n_episodes} episodes)

{tab}
{warn}
### 4.5 Statistical comparison

Family: every algorithm against GNN-DRL, {b['family']['n_comparisons']} comparisons,
Bonferroni threshold alpha = {pfmt(b['family']['bonferroni_threshold'])}.

{comparison_table(b['family'], 4)}

### 4.6 Recommended wording

The previous draft claimed that *"DQN converges fastest ... GNN-DRL achieves the highest
asymptotic reward (approximately 95 % of optimum) ... MADRL/QMIX ... approximately 92 %
of optimum ... Federated DQN ... within 5 % of centralised DQN"*. **None of those
figures is supported by this campaign and all of them must be deleted.** The measured
ordering of the final normalised score is
{', '.join(f"{a} = {f(s[a]['mean'], 3)}" for a in sorted(algos, key=lambda x: -s[x]['mean']))}.

Suggested replacement:

> Four learning-based controllers were implemented in full -- a Deep Q-Network, a
> QMIX-style multi-agent variant, a federated-averaging variant and a graph
> neural-network variant -- and trained for {RLTRAIN.n_episodes} episodes on
> {b['n_seeds']} independent seeds. Performance is reported on a normalised scale on
> which zero corresponds to uniformly random power control and one to a per-slot greedy
> oracle with full instantaneous channel state information. {best} attained the highest
> final score ({ci(s[best], '', 3)}).
{'> Within the training budget used here, ' + ', '.join(not_conv) + ' did not satisfy the convergence criteria in the majority of runs, and no claim of convergence is made for ' + ('it' if len(not_conv) == 1 else 'them') + '.' if not_conv else ''}
> Differences between the controllers that do not survive the Bonferroni correction are
> reported as not significant.

### 4.7 What this does and does not show

**It does show** that four genuinely distinct learning architectures, implemented from
first principles and verified by gradient checking, can be trained on a multi-cell
power-control problem with queue dynamics, and how far each gets relative to two
well-defined references within an equal and explicitly stated training budget.

**It does not show** that any of these controllers is state of the art, that the
ranking would survive a larger training budget or a hyper-parameter search (all four use
identical hyper-parameters, which is fair but not optimal for any of them), or that the
ranking transfers to a different environment. The environment is a stylised four-cell
model, not a system-level 5G deployment. The oracle normaliser has full CSI that the
agents lack, so a score of 1.0 is not attainable by any of them.

---
"""


def sec_slicing(b: dict) -> str:
    if b is None:
        return ""
    loads = b["loads"]
    names = {"hard": "Hard isolation", "soft": "Soft isolation", "umro": "UMRO-5G (Lagrangian)"}
    rows = []
    for l in loads:
        blk = b["per_load"][str(l)]
        r = [f(l, 1)]
        for st in names:
            r.append(f(blk["throughput_mbps"]["summary"][st]["mean"], 2))
        for st in names:
            r.append(f(blk["utilisation"]["summary"][st]["mean"], 3))
        for st in names:
            r.append(f(100 * blk["urllc_violation"]["summary"][st]["mean"], 2))
        rows.append(r)
    tab = table(["rho"] + [f"{v} thr (Mbit/s)" for v in names.values()]
                + [f"{v} util" for v in names.values()]
                + [f"{v} URLLC viol (%)" for v in names.values()], rows)

    hi = b["per_load"][str(loads[-1])]
    detail_rows = []
    for st in names:
        detail_rows.append([names[st],
                            msd(hi["throughput_mbps"]["summary"][st], "Mbit/s", 2),
                            msd(hi["utilisation"]["summary"][st], "", 4),
                            msd(hi["urllc_violation"]["summary"][st], "", 4)])
    detail = table(["Strategy", "Aggregate throughput", "PRB utilisation",
                    "URLLC violation probability"], detail_rows)

    return f"""## 5. Multi-slice resource allocation (Section 8.4)

Single 20 MHz, {NUM_MU0.n_prb}-PRB cell at mu = {NUM_MU0.mu}, three slices, offered
load swept from {f(loads[0], 1)} to {f(loads[-1], 1)}, {b['n_seeds']} seeds,
{CAMPAIGN.n_monte_carlo} Monte Carlo iterations averaged inside each seed. Within a
load point all three allocators replay the same demand and channel draws.

The Lagrangian dual reached its stopping criterion (relative primal residual
<= {SLICING.dual_tolerance}) in {f(100 * b['dual_converged_fraction'], 1)} % of the
timeslots in which it was invoked.

### 5.1 Results across the load sweep

{tab}

### 5.2 Detail at rho = {f(loads[-1], 1)}

{detail}

### 5.3 Statistical comparison

Family: UMRO-5G against each baseline at rho = 0.8 and rho = 1.0 on three metrics,
{b['family']['n_comparisons']} comparisons, Bonferroni threshold
alpha = {pfmt(b['family']['bonferroni_threshold'])}.

{comparison_table(b['family'], 4)}

### 5.4 What this does and does not show

**It does show** how a warm-started Lagrangian dual allocator behaves against a static
partition and a fixed-pool proportional split, on identical demand realisations, across
the whole load range, with confidence intervals over {b['n_seeds']} independent seeds.

**It does not show** end-to-end behaviour: this experiment models a slot as an
instantaneous demand/capacity match and does not simulate per-user queues, scheduling
or delay. The URLLC "violation" here is a resource-shortfall indicator (the URLLC slice
receives less than 95 % of the PRBs its instantaneous demand requires), not a measured
packet delay. The measured delay results are in Section 3.

---
"""


def sec_scheduling(b: dict) -> str:
    if b is None:
        return ""
    s = b["summaries"]
    algos = list(s["throughput_mbps"].keys())
    pretty = {"round_robin": "Round Robin", "max_rate": "Maximum Rate",
              "proportional_fair": "Proportional Fair",
              "learned": "Learned (policy gradient)"}
    rows = []
    for a in algos:
        rows.append([pretty.get(a, a),
                     ci(s["throughput_mbps"][a], "", 2),
                     ci(s["jain"][a], "", 4),
                     ci(s["p5_mbps"][a], "", 3),
                     ci(s["cell_edge_mbps"][a], "", 3),
                     f(s["starved_users"][a]["mean"], 2)])
    tab = table(["Algorithm", "Aggregate throughput (Mbit/s)", "Jain fairness index",
                 "5th-percentile user rate (Mbit/s)",
                 "Cell-edge rate, worst 10 % (Mbit/s)", "Starved users"], rows)
    return f"""## 6. Scheduling algorithm comparison (Section 8.6, Table 11)

{SCHED.n_users} users, {NUM_MU1_SCHED.n_prb} PRBs at
{f(NUM_MU1_SCHED.scs_khz, 0)} kHz, mean SNR uniform on
[{f(SCHED.snr_db_low, 0)}, {f(SCHED.snr_db_high, 0)}] dB, {SCHED.n_tti} TTIs,
{b['n_seeds']} seeds. All four schedulers consume the **same** pre-generated
spectral-efficiency trace, so the comparison is paired at the TTI level as well as at
the seed level.

{tab}

### 6.1 Statistical comparison

Family: every scheduler against Proportional Fair on four metrics,
{b['family']['n_comparisons']} comparisons, Bonferroni threshold
alpha = {pfmt(b['family']['bonferroni_threshold'])}.

{comparison_table(b['family'], 4, pretty)}

### 6.2 Recommended wording

The previous draft concluded that the results *"validate the theoretical optimality
properties of PF scheduling"*. **They do not, and Reviewer 1 comment 9 is right about
this.** A finite-horizon simulation on one channel model cannot validate an asymptotic
optimality property. What the experiment shows is an empirical throughput/fairness
trade-off ordering. Suggested replacement:

> Proportional Fair occupied the expected intermediate position on the
> throughput/fairness trade-off, delivering
> {f(100 * s['throughput_mbps']['proportional_fair']['mean'] / s['throughput_mbps']['max_rate']['mean'], 1)} %
> of the aggregate throughput of Maximum Rate at a Jain fairness index of
> {f(s['jain']['proportional_fair']['mean'], 3)} against
> {f(s['jain']['max_rate']['mean'], 3)} for Maximum Rate. These measurements are
> consistent with the known properties of the proportional-fair metric; they are an
> empirical observation on this channel model and this horizon, not a proof of
> asymptotic optimality.

The learned scheduler is a **policy-gradient (REINFORCE) scheduler with a two-layer
network scoring per-user features**, trained online against the sum-log-rate objective.
It is not a DQN and the article must not call it one without qualification.

### 6.3 What this does and does not show

**It does show** the throughput, fairness, 5th-percentile and cell-edge behaviour of
four schedulers on identical fading traces, with paired statistics over
{b['n_seeds']} seeds.

**It does not show** anything about optimality, about behaviour under non-full-buffer
traffic (this experiment is full buffer), or about multi-cell interference. The learned
scheduler was given the objective, not the rule, but it was trained within each run and
its result therefore mixes learning speed with asymptotic quality.

---
"""


def sec_sfc(b: dict) -> str:
    if b is None:
        return ""
    rows = []
    for r in b["rows"]:
        if not r.get("stable"):
            rows.append([f(r["lambda_pps"], 0), "unstable", "-", "-", "-", "-"])
            continue
        rows.append([f(r["lambda_pps"], 0),
                     f(r["rho_bottleneck"], 3),
                     f(r["analytical"]["mean"], 4),
                     ci(r["des"], "", 4),
                     f(r["rel_error_pct"]["mean"], 3),
                     pfmt(r["paired_test"]["p_raw"])])
    tab = table([f"lambda (packets/s)", "Bottleneck utilisation",
                 "Analytical mean latency (ms)", "Simulated mean latency (ms)",
                 "Relative error (%)", "Paired p (DES vs analytical)"], rows)
    stable = [r for r in b["rows"] if r.get("stable")]
    worst = max(stable, key=lambda r: abs(r["rel_error_pct"]["mean"]))
    return f"""## 7. SFC latency: analytical model vs discrete-event simulation (Section 8.7)

A {len(SFC.vnf_names)}-VNF open tandem ({' -> '.join(SFC.vnf_names)}) with service
rates {tuple(int(v) for v in SFC.service_rates_pps)} packets/s. The analytical arm is
the Jackson-network mean plus the exact hypoexponential tail; the simulation arm is a
FIFO discrete-event simulator built on the Lindley recursion, which is exact rather
than approximate. {SFC.n_packets_des:,} packets per replication, the first
{f(100 * SFC.warmup_fraction, 0)} % discarded as transient, {b['n_seeds']} seeds.

> **Parameter deviation, declared.** The article's own service rates sit inside an OMML
> equation object that text extraction cannot recover, and the numbers it reports are
> mutually inconsistent: a five-stage M/M/1 chain whose bottleneck saturates inside a
> 50-350 packet/s sweep has a **zero-load** latency of 8.8 ms and therefore cannot
> deliver the 0.65 ms at 200 packets/s that the draft claims. A self-consistent
> parameterisation preserving the ratios between the five VNFs was used instead, and
> the arrival sweep was rescaled accordingly.

{tab}

The largest discrepancy between the model and the simulation over the stable range was
**{f(abs(worst['rel_error_pct']['mean']), 2)} %** at lambda =
{f(worst['lambda_pps'], 0)} packets/s. The bottleneck VNF has
mu = {f(b['bottleneck_mu_pps'], 0)} packets/s. The largest arrival rate whose analytical
mean end-to-end chain latency stays inside the {f(SFC.urllc_budget_ms, 0)} ms radio
budget is **{f(b['max_lambda_for_1ms_pps'], 0)} packets/s**.

### 7.1 What this does and does not show

**It does show** that the Jackson/M/M/1 decomposition predicts the mean end-to-end
latency of this chain to within the tabulated relative error over the whole stable
load range, and it gives the exact load at which the chain stops meeting a 1 ms budget.

**It does not show** that a real VNF chain behaves as M/M/1: exponential service times,
Poisson arrivals, infinite buffers, and single-server FIFO discipline are all
modelling assumptions. Real NFV service times are typically less variable than
exponential, so the model is conservative. Burke's theorem, which makes the tandem a
Jackson network, holds only in the stationary regime; the transient at the start of each
replication is discarded rather than modelled.

---
"""


def sec_energy(b: dict) -> str:
    if b is None:
        return ""
    labels = {"always_on": "Always-on", "static_sleep": "Static scheduled sleep",
              "predictive_sleep": "Predictive sleep (Holt forecaster)"}
    scales = [str(s) for s in b["demand_scales"]]
    rows = []
    for sc in scales:
        r = [sc]
        for st in labels:
            d = b["points"][sc][st]
            r.append(f(d["mean_throughput_mbps"]["mean"], 1))
        for st in labels:
            d = b["points"][sc][st]
            r.append(f(d["energy_efficiency_mbit_per_j"]["mean"], 3))
        for st in labels:
            r.append(f(100 * b["points"][sc][st]["sla_feasible_fraction"], 0) + " %")
        rows.append(r)
    tab = table(["Demand scale"] + [f"{v} thr (Mbit/s)" for v in labels.values()]
                + [f"{v} EE (Mbit/J)" for v in labels.values()]
                + [f"{v} SLA-feasible" for v in labels.values()], rows)

    nominal = "1.0"
    det_rows = []
    for st in labels:
        d = b["points"][nominal][st]
        det_rows.append([labels[st],
                         msd(d["energy_efficiency_mbit_per_j"], "Mbit/J", 3),
                         msd(d["mean_throughput_mbps"], "Mbit/s", 2),
                         msd(d["energy_kwh"], "kWh/day", 2),
                         f(d["mean_active_oru"]["mean"], 2),
                         f(100 * d["max_blocking"]["mean"], 3),
                         f"{f(100 * d['sla_feasible_fraction'], 0)} %"])
    det = table(["Strategy", "Energy efficiency", "Mean throughput", "Daily energy",
                 "Mean active O-RUs", "Peak blocking (%)", "SLA-feasible seeds"],
                det_rows)

    mrows = []
    for m in b["margin_sweep"]:
        mrows.append([f(100 * m["margin"], 0) + " %",
                      ci(m["ee"], "", 3),
                      ci(m["throughput"], "", 1),
                      f(100 * m["max_blocking"]["mean"], 3),
                      f"{f(100 * m['sla_feasible_fraction'], 0)} %"])
    msweep = table(["Safety margin", "Energy efficiency (Mbit/J)",
                    "Mean throughput (Mbit/s)", "Peak blocking (%)",
                    "SLA-feasible seeds"], mrows)

    mape = b["points"][nominal]["predictive_sleep"]["forecast_mape_pct"]
    ee_p = b["points"][nominal]["predictive_sleep"]["energy_efficiency_mbit_per_j"]["mean"]
    ee_a = b["points"][nominal]["always_on"]["energy_efficiency_mbit_per_j"]["mean"]
    ee_s = b["points"][nominal]["static_sleep"]["energy_efficiency_mbit_per_j"]["mean"]

    return f"""## 8. Energy efficiency and adaptive cell sleeping (Section 8.9, Figure 6)

**Answers Reviewer 1 comment 8 for Figure 3 of the previous draft.**

### 8.1 Model

{ENERGY.n_oru} O-RUs, {int(24 * 60 / ENERGY.slot_minutes)} slots of
{f(ENERGY.slot_minutes, 0)} minutes over one day. Power follows the EARTH
load-dependent model,

```
P_site(t) = n_active(t) * (P_static + P_slope * u(t)) + (N - n_active(t)) * P_sleep + P_overhead
E         = sum_t P_site(t) * T_slot + n_wakeups * E_wake
```

with P_static = {f(ENERGY.p_active_static_w, 0)} W, P_slope =
{f(ENERGY.p_load_slope_w, 0)} W (so a fully loaded O-RU draws
{f(ENERGY.p_active_w, 0)} W, the value used in the previous draft), P_sleep =
{f(ENERGY.p_sleep_w, 0)} W, P_overhead = {f(ENERGY.p_overhead_w, 0)} W and a wake-up
cost of {f(ENERGY.wake_energy_j, 0)} J per O-RU transition. Sleeping is therefore not
free.

Three strategies: **always-on**; **static scheduled sleep** (a fixed
{f(ENERGY.static_sleep_fraction * 100, 0)} % of O-RUs sleep between
{f(ENERGY.static_sleep_start_hour, 0)}:00 and {f(ENERGY.static_sleep_end_hour, 0)}:00,
open loop); and **predictive sleep**, in which a one-slot-ahead demand forecast with a
configurable safety margin sets the number of active O-RUs.

> **The forecaster is Holt's linear-trend exponential smoothing (alpha =
> {ENERGY.holt_alpha}, beta = {ENERGY.holt_beta}), a two-parameter recursive predictor.
> It is NOT an LSTM.** The previous draft's claim of "LSTM-based traffic prediction
> models" is not reproduced by this code and must be reworded. The measured
> one-slot-ahead forecast error of the Holt predictor was
> {ci(mape, '%', 2)} MAPE.

All three strategies see the **identical** demand realisation within a seed.

### 8.2 Energy efficiency and throughput across the demand sweep

{tab}

### 8.3 Detail at the nominal demand point (scale 1.0)

{det}

### 8.4 Safety-margin sensitivity of the predictive strategy

{msweep}

### 8.5 Statistical comparison

Family: predictive sleep against each baseline on energy efficiency and throughput at
the nominal point, {b['family']['n_comparisons']} comparisons, Bonferroni threshold
alpha = {pfmt(b['family']['bonferroni_threshold'])}.

{comparison_table(b['family'], 4, labels)}

### 8.6 Recommended wording

The previous draft claimed *"approximately 14 Mbits/Joule energy efficiency -- a 3x
improvement over the Always-On baseline -- while maintaining 4.2 bps/Hz aggregate
throughput"* and attributed the gain to "LSTM-based traffic prediction". **Delete all
of it.** The measured values at the nominal demand point are: predictive
{f(ee_p, 3)} Mbit/J, static sleep {f(ee_s, 3)} Mbit/J, always-on {f(ee_a, 3)} Mbit/J,
i.e. a factor of **{f(ee_p / ee_a, 2)}x** over always-on, not 3x. Suggested
replacement:

> Adaptive cell sleeping driven by a Holt exponential-smoothing traffic forecaster
> raised the energy efficiency of the modelled {ENERGY.n_oru}-O-RU cluster from
> {ci(b['points'][nominal]['always_on']['energy_efficiency_mbit_per_j'], 'Mbit/J', 3)}
> under an always-on policy to
> {ci(b['points'][nominal]['predictive_sleep']['energy_efficiency_mbit_per_j'], 'Mbit/J', 3)},
> a factor of {f(ee_p / ee_a, 2)}, at the nominal demand point over {b['n_seeds']}
> independent seeds. The gain is bounded by the fixed pool and cooling overhead of
> {f(ENERGY.p_overhead_w, 0)} W, which no sleeping policy can remove.

### 8.7 What this does and does not show

**It does show** the energy-efficiency/throughput trade-off of three sleeping policies
under an explicit, fully specified power model with a non-zero wake-up cost, with
confidence intervals over {b['n_seeds']} seeds and with SLA feasibility marked at each
operating point, plus the sensitivity of the predictive policy to its one free
parameter.

**It does not show** measurements from real hardware; the O-RU power figures are the
ones the previous draft asserted, combined with the EARTH load-dependent model, and
they are model parameters rather than measurements. Sleep-mode transition *latency* is
modelled only as a one-slot delay, and no impact on user-plane latency or on handover
is simulated. The 15-minute slot resolution cannot represent short-timescale sleeping
(micro-sleep or symbol-level sleeping), which is where much of the practical gain in
the literature comes from. Coverage is treated as a pure capacity constraint: an O-RU
that sleeps is assumed to leave no coverage hole, which is optimistic.

---
"""


def sec_ris(b: dict) -> str:
    if b is None:
        return ""
    labels = {"no_ris": "No RIS", "random_phase": "Random phases",
              "alternating_opt": "Alternating optimization"}
    rows = []
    for n in b["n_ris_sweep"]:
        blk = b["points"][str(n)]
        r = [str(n)]
        for arm in labels:
            r.append(f(blk[arm]["se_bps_hz"]["mean"], 4))
        for arm in labels:
            r.append(f(100 * blk[arm]["urllc_violation"]["mean"], 2))
        r.append(f(blk["ao_gain_pct"]["mean"], 1))
        r.append(f(blk["ao_mean_iterations"]["mean"], 1))
        r.append(f(100 * blk["ao_converged_fraction"], 1))
        rows.append(r)
    tab = table(["N_RIS"] + [f"{v} SE (bit/s/Hz)" for v in labels.values()]
                + [f"{v} outage (%)" for v in labels.values()]
                + ["AO gain over no RIS (%)", "AO iterations", "AO converged (%)"],
                rows)

    big = str(b["n_ris_sweep"][-1])
    det_rows = []
    for arm in labels:
        d = b["points"][big][arm]
        det_rows.append([labels[arm],
                         msd(d["se_bps_hz"], "bit/s/Hz", 4),
                         msd(d["throughput_mbps"], "Mbit/s", 2),
                         msd(d["urllc_violation"], "", 4)])
    det = table(["Arm", "Spectral efficiency", "Throughput over 20 MHz",
                 "URLLC rate-outage probability"], det_rows)

    a = b["assumptions"]
    gain_big = b["points"][big]["ao_gain_pct"]["mean"]
    return f"""## 9. RIS-assisted beamforming (Section 8.10, Figure 7)

**Answers Reviewer 1 comment 8 for Figure 4 of the previous draft.**

### 9.1 Model and assumptions, stated plainly

Signal model `y_k = (h_d,k^H + h_r,k^H Theta G) w s + n` with M =
{RIS.n_bs_antennas} gNB antennas, K = {RIS.n_users} UEs and N_RIS in
{RIS.n_ris_sweep}. The direct gNB-UE link is Rayleigh with path-loss exponent
{RIS.pl_exponent_direct}; the gNB-RIS and RIS-UE links are Rician with a
{f(RIS.rician_k_db, 0)} dB factor and exponents {RIS.pl_exponent_bs_ris} and
{RIS.pl_exponent_ris_ue}. Transmit power is calibrated so the **no-RIS** arm sees the
{f(RIS.direct_snr_db, 0)} dB average receive SNR quoted in the previous draft; all
three arms then use the same power. {b['n_seeds']} seeds,
{RIS.n_realizations} channel realisations per seed per element count.

| Assumption | Value |
|---|---|
| Channel state information | {a['csi']} |
| Phase resolution | {a['phase_resolution']} |
| Scheduling | {a['scheduling']} |
| Path-loss exponents (direct / gNB-RIS / RIS-UE) | {a['pathloss_exponents']['direct']} / {a['pathloss_exponents']['bs_ris']} / {a['pathloss_exponents']['ris_ue']} |
| Cascade Rician factor | {f(a['rician_k_db'], 0)} dB |
| Bandwidth | {f(RIS.bandwidth_mhz, 0)} MHz, narrowband flat fading |

> **Perfect CSI makes every RIS number below an upper bound.** No channel-estimation
> overhead, no estimation error and no phase quantisation are modelled in the default
> configuration. The article must say so in the same sentence as the numbers.

**Alternating optimization**: step 1 sets the active beamformer to the maximum-ratio
transmitter for the current phases; step 2 sets each element's phase in closed form to
co-phase its contribution with the direct path,
`theta_n = angle(h_d^H w) - angle(conj(h_r,n) (G w)_n)`. The two steps alternate until
the **relative change in the effective channel gain falls below {RIS.ao_tolerance}** or
{RIS.ao_max_iter} iterations are reached. Both the achieved iteration count and the
convergence flag are measured and reported in the table below.

### 9.2 Results

{tab}

### 9.3 Detail at N_RIS = {big}

{det}

### 9.4 Statistical comparison

Family: alternating optimization against the other two arms, at N_RIS = 64 and 512, on
spectral efficiency and URLLC outage, {b['family']['n_comparisons']} comparisons,
Bonferroni threshold alpha = {pfmt(b['family']['bonferroni_threshold'])}.

{comparison_table(b['family'], 4, labels)}

### 9.5 Recommended wording

The previous draft claimed *"up to 80 % throughput gain over the no-RIS baseline at
N_RIS = 512, while reducing URLLC violation probability from 1.5 % to below 0.8 %"*.
**The 80 % figure is not what this model produces**: the measured gain at N_RIS =
{big} is {f(gain_big, 0)} %, because a co-phased RIS array delivers a beamforming gain
that grows quadratically in the number of elements. The larger number is not a
better result -- it is a direct consequence of the perfect-CSI assumption, and must be
presented as such. Suggested replacement:

> Under perfect channel state information and continuous phase shifts, alternating
> optimization of the active beamformer and the passive phase profile raised the
> spectral efficiency of the modelled cell-edge link from
> {ci(b['points'][big]['no_ris']['se_bps_hz'], 'bit/s/Hz', 4)} without a RIS to
> {ci(b['points'][big]['alternating_opt']['se_bps_hz'], 'bit/s/Hz', 4)} at
> N_RIS = {big}, and reduced the rate-outage probability from
> {ci(b['points'][big]['no_ris']['urllc_violation'], '', 4)} to
> {ci(b['points'][big]['alternating_opt']['urllc_violation'], '', 4)}. The alternating
> optimization converged in {f(b['points'][big]['ao_mean_iterations']['mean'], 1)}
> iterations on average against a relative tolerance of {RIS.ao_tolerance}. These
> figures are upper bounds: they assume perfect instantaneous knowledge of the direct,
> gNB-RIS and RIS-UE channels, which is the single strongest assumption in the RIS
> literature and is not achievable in a deployed system.

### 9.6 What this does and does not show

**It does show** how the beamforming gain of a passive RIS scales with the number of
elements when the phases are optimally co-phased, how much of that gain a random phase
profile captures (very little, as the table shows), how many alternating-optimization
iterations convergence takes, and what all of that does to a rate-outage probability
defined against an explicit URLLC rate requirement of
{f(RIS.urllc_rate_req_bps_per_hz, 1)} bit/s/Hz.

**It does not show** achievable performance in a deployed system. Perfect CSI is
assumed; channel estimation for a passive RIS with hundreds of elements is the central
unsolved problem of the field and its overhead scales with N_RIS. Phase shifts are
continuous; practical surfaces use 1-2 bit quantisation. The model is narrowband and
single-cell, with one scheduled user per resource, so no multi-user interference, no
frequency selectivity and no inter-cell RIS interference are represented. Nothing here
addresses the control-plane question of how a RIC would reconfigure a surface within a
{f(INTEGRATED.medium_period_ms, 0)} ms medium-loop budget.

---
"""


def sec_complexity(b: dict) -> str:
    if b is None:
        return ""
    rows = []
    for r in b["rows"]:
        to = r["bnb_timeout_fraction"]
        bnb = ci(r["branch_and_bound"], "", 1)
        if to > 0:
            bnb = f"{f(r['branch_and_bound']['mean'], 1)} (**timeout**, lower bound)"
        rows.append([r["n"],
                     ci(r["learned_inference"], "", 4),
                     ci(r["water_filling"], "", 4),
                     bnb,
                     f"{f(100 * to, 0)} %",
                     f(r["speedup_vs_water_filling"]["mean"], 1),
                     f(r["speedup_vs_branch_and_bound"]["mean"], 0)])
    tab = table(["N", "Learned inference (ms)", "Water-filling (ms)",
                 "Branch and bound (ms)", "B&B timed out",
                 "Speedup vs water-filling", "Speedup vs B&B"], rows)

    wf = [r["speedup_vs_water_filling"]["mean"] for r in b["rows"]]
    bb = [r["speedup_vs_branch_and_bound"]["mean"] for r in b["rows"]]
    first_to = next((r["n"] for r in b["rows"] if r["bnb_timeout_fraction"] > 0), None)
    return f"""## 10. Computational complexity (Section 8.8, Table 12)

**Answers Reviewer 1 comment 9.**

Wall-clock decision time measured with `time.perf_counter` around three real
procedures, each warmed up before measurement, {COMPLEXITY.n_repeats} repetitions per
point, median reported, **{b['n_seeds']} seeds run sequentially on an otherwise idle
machine with BLAS pinned to one thread** (running the replications concurrently would
measure CPU contention rather than algorithmic cost, which is why this stage uses fewer
seeds than the rest of the campaign; its confidence intervals carry df =
{b['n_seeds'] - 1}).

* **Learned inference** -- one forward pass of an [N -> 64 -> 64 -> N] policy network,
  the operation a Near-RT RIC xApp performs per decision.
* **Water-filling** -- bisection on the water level to a relative tolerance of
  {COMPLEXITY.wf_tolerance}, O(N) per bisection step.
* **Branch and bound** -- exact solution of a strongly correlated binary knapsack
  (c_i = w_i + 100), the classical hard family, with the LP relaxation bound and
  incumbent pruning, under a **{f(b['timeout_s'], 0)} s wall-clock timeout**.

{tab}

{b['note']}

### 10.1 The 100-1000x claim

The previous draft asserted that the results *"quantitatively validate the 100-1000x
latency advantage of DRL over classical MILP solvers"*. **The measurement does not
support that as stated, in either direction:**

* Against **water-filling**, the measured speedup ranged from **{f(min(wf), 1)}x to
  {f(max(wf), 1)}x** -- one to two orders of magnitude *below* the claimed range. Both
  procedures are dominated by fixed interpreter and array-allocation overhead at
  N <= {COMPLEXITY.n_sweep[-1]}, so neither exhibits its asymptotic scaling in this
  range. That is itself worth stating.
* Against **branch and bound**, the measured ratio reached
  **{f(max(bb), 0)}x**, which is far *above* the claimed range, and is a lower bound
  because branch and bound hit the {f(b['timeout_s'], 0)} s timeout from
  N = {first_to} upwards without proving optimality.

Suggested replacement:

> Decision time was measured directly for the three procedures. A single policy-network
> inference took
> {ci(b['rows'][0]['learned_inference'], 'ms', 4)} at N = {b['rows'][0]['n']} and
> {ci(b['rows'][-1]['learned_inference'], 'ms', 4)} at N = {b['rows'][-1]['n']},
> growing only linearly in the problem size. Iterative water-filling was
> {f(min(wf), 1)}x to {f(max(wf), 1)}x slower over the same range; at these problem
> sizes both are dominated by fixed per-call overhead rather than by their asymptotic
> complexity. Exact branch-and-bound solution of the corresponding binary
> resource-assignment problem exceeded a {f(b['timeout_s'], 0)} s budget from
> N = {first_to} onwards, so for N >= {first_to} its reported times are lower bounds and
> the corresponding speedup figures, which exceed 10^5, are lower bounds as well. The
> earlier claim of a uniform 100-1000x advantage is not supported and has been removed.

### 10.2 What this does and does not show

**It does show** measured, reproducible decision times for three concrete
implementations on one machine, and the problem size at which exact combinatorial
optimisation becomes infeasible under a stated time budget.

**It does not show** a language- or implementation-independent complexity comparison.
All three procedures are NumPy/Python; a C or GPU implementation would shift all three
curves, though not their relative asymptotics. The branch-and-bound instance is a
deliberately hard knapsack family, not the article's MINLP, and a commercial solver with
cutting planes and presolve would do better than this textbook implementation. The
learned-inference time excludes training, which is the cost that a learned controller
pays once.

---
"""


def sec_consolidated(integ, learn, sched, energy_, ris_, cx, sf) -> str:
    rows = []
    if integ:
        s = integ["summaries"]
        rows.append(["Integrated end-to-end (Section 8.3)",
                     "SLA satisfaction rate, full UMRO-5G",
                     ci(s["sla_satisfaction_rate"]["E_full_umro"], "", 3),
                     f"vs {ci(s['sla_satisfaction_rate']['A_hard_static'], '', 3)} for static hard isolation"])
        rows.append(["", "Aggregate throughput, full UMRO-5G",
                     ci(s["aggregate_throughput_mbps"]["E_full_umro"], "Mbit/s", 2),
                     f"vs {ci(s['aggregate_throughput_mbps']['A_hard_static'], 'Mbit/s', 2)}"])
        rows.append(["", "PRB utilisation, full UMRO-5G",
                     ci(s["prb_utilisation"]["E_full_umro"], "", 4), ""])
        rows.append(["", "URLLC radio violation probability, full UMRO-5G",
                     ci(s["urllc_violation_prob"]["E_full_umro"], "", 5),
                     "the symmetric t interval is not truncated at zero; read the "
                     "lower limit as 0 (see Section 1.2). Compare "
                     + ci(s["urllc_violation_prob"]["C_no_medium"], "", 5)
                     + " without the medium loop"])
    if learn:
        best = max(learn["summaries"], key=lambda a: learn["summaries"][a]["mean"])
        rows.append(["Learning controllers (Section 8.5)",
                     f"Best final normalised score ({best})",
                     ci(learn["summaries"][best], "", 3),
                     "0 = random policy, 1 = myopic full-CSI oracle"])
    if sched:
        s = sched["summaries"]
        rows.append(["Scheduling (Section 8.6)", "Proportional Fair throughput",
                     ci(s["throughput_mbps"]["proportional_fair"], "Mbit/s", 2),
                     f"Jain {f(s['jain']['proportional_fair']['mean'], 3)}"])
    if sf:
        stable = [r for r in sf["rows"] if r.get("stable")]
        worst = max(stable, key=lambda r: abs(r["rel_error_pct"]["mean"]))
        rows.append(["SFC latency (Section 8.7)",
                     "Worst analytical-vs-simulation relative error",
                     f"{f(abs(worst['rel_error_pct']['mean']), 2)} %",
                     f"at lambda = {f(worst['lambda_pps'], 0)} packets/s"])
    if cx:
        wf = [r["speedup_vs_water_filling"]["mean"] for r in cx["rows"]]
        bb = [r["speedup_vs_branch_and_bound"]["mean"] for r in cx["rows"]]
        rows.append(["Complexity (Section 8.8)", "Learned inference vs water-filling",
                     f"{f(min(wf), 1)}x to {f(max(wf), 1)}x", "measured, not asserted"])
        rows.append(["", "Learned inference vs branch and bound",
                     f"up to {f(max(bb), 0)}x",
                     f"lower bound; B&B timed out at {f(cx['timeout_s'], 0)} s"])
    if energy_:
        p = energy_["points"]["1.0"]
        rows.append(["Energy (Section 8.9)", "Energy efficiency, predictive sleep",
                     ci(p["predictive_sleep"]["energy_efficiency_mbit_per_j"], "Mbit/J", 3),
                     f"vs {ci(p['always_on']['energy_efficiency_mbit_per_j'], 'Mbit/J', 3)} always-on"])
    if ris_:
        big = str(ris_["n_ris_sweep"][-1])
        rows.append(["RIS (Section 8.10)",
                     f"Spectral efficiency, alternating optimization at N_RIS = {big}",
                     ci(ris_["points"][big]["alternating_opt"]["se_bps_hz"], "bit/s/Hz", 4),
                     f"vs {ci(ris_['points'][big]['no_ris']['se_bps_hz'], 'bit/s/Hz', 4)} no RIS; perfect CSI"])
    return f"""## 11. Consolidated summary (ready for Table 13 of the article)

{table(["Experiment", "Metric", "Value (mean, 95 % CI)", "Reference / caveat"], rows)}

---
"""


def sec_claims(integ, learn, energy_, ris_, cx) -> str:
    lines = []

    def add(where, old, new):
        lines.append(f"""### {where}

**Current text (delete):** {old}

**Recommended replacement:** {new}
""")

    if integ:
        s = integ["summaries"]
        add("Section 8.4, throughput claim",
            '"The UMRO-5G dynamic allocation consistently achieves 15-25 % higher '
            'aggregate throughput than Hard Isolation at high loads. At rho = 1.0, Hard '
            'Isolation achieves approximately 44 Mbps aggregate throughput, Soft '
            'Isolation achieves ~50 Mbps, and UMRO-5G achieves ~54 Mbps."',
            "replace with the measured values in Section 5 of this file, which come "
            "from the executed sweep and carry confidence intervals; state the load "
            "point explicitly and do not use the word 'consistently' unless the "
            "comparison is significant after correction at every load point.")
        add("Section 8.3 / Conclusions, framework validation",
            '"validation of the complete framework"',
            "the integrated runner in Section 3 of this file is an end-to-end "
            "*simulation* of the three loops, not a validation. Use: 'the three control "
            "loops were executed together on a single clock over a compressed 24-hour "
            "traffic profile, and the contribution of each outer loop was measured by "
            "ablation'.")
    if learn:
        add("Section 8.5, DRL claims",
            '"DQN converges fastest (within ~500 episodes) ... GNN-DRL achieves the '
            'highest asymptotic reward (approximately 95 % of optimum) ... MADRL/QMIX '
            '... approximately 92 % ... Federated DQN ... within 5 % of centralized DQN"',
            "use the measured normalised scores in Section 4.4, state the normaliser "
            "explicitly (random policy = 0, myopic full-CSI oracle = 1), and report "
            "non-convergence where it was measured. Delete every 'percentage of "
            "optimum' figure.")
        add("Section 8.5, methodology note",
            '"The convergence curves are generated using simplified tabular proxy '
            'agents ... These are not full neural network implementations."',
            "delete the note entirely and replace it with the implementation "
            "description in Section 4.1 of this file. The agents are now real.")
    add("Section 8.6, PF optimality",
        '"These results validate the theoretical optimality properties of PF scheduling"',
        "see Section 6.2 of this file. A finite simulation cannot validate an "
        "asymptotic optimality property; report the measured trade-off instead.")
    if cx:
        add("Section 8.8, speedup",
            '"These results quantitatively validate the 100-1000x latency advantage of '
            'DRL over classical MILP solvers for real-time decision-making."',
            "see Section 10.1 of this file. Report the measured range against "
            "water-filling and the lower bound against branch and bound, and say that "
            "the branch-and-bound entries are timeouts.")
    if energy_:
        add("Section 9.4 / Figure 3, energy",
            '"LSTM-based traffic prediction models enable proactive anticipation of '
            'low-load periods, achieving energy consumption reductions of 20-40 % in '
            'real-world deployments" and "approximately 14 Mbits/Joule ... a 3x '
            'improvement over the Always-On baseline"',
            "see Section 8.6 of this file. The forecaster implemented here is Holt "
            "exponential smoothing, not an LSTM; the measured improvement factor is "
            "reported there. If the 20-40 % figure is retained it must be attributed to "
            "the cited literature in the same sentence and marked as "
            "reference-derived, not as a result of this work.")
    if ris_:
        add("Section 9.5 / Figure 4, RIS",
            '"AO-based RIS optimization achieves up to 80 % throughput gain over the '
            'no-RIS baseline at N_RIS = 512, while reducing URLLC violation probability '
            'from 1.5 % to below 0.8 %"',
            "see Section 9.5 of this file. Report the measured gain with the "
            "perfect-CSI caveat in the same sentence.")
    add("Section 8.2, sample size",
        '"The effective sample size for each metric is N_seeds x N_MONTE_CARLO = 5 x '
        '1,000 = 5,000 realizations per load point"',
        "see Section 1.1 of this file. The effective sample size is the number of "
        "seeds.")
    add("Section 1, novelty",
        '"first comprehensive" and similar superlatives',
        "outside the scope of the simulation work, but note that nothing in this "
        "campaign supports a priority claim; the simulation section must not be cited "
        "in support of one.")
    return "## 12. Claims that must be weakened or deleted\n\n" + "\n".join(lines) + "\n---\n"


def sec_provenance(blobs: dict, manifest: dict) -> str:
    orig = []
    for name, fig, sect in [
        ("fig4_integrated.png", "Figure 4", "8.3"),
        ("fig5_convergence.png", "Figure 5", "8.5"),
        ("fig6_energy.png", "Figure 6", "8.9"),
        ("fig7_ris.png", "Figure 7", "8.10"),
        ("figS1_multislice.png", "Supporting figure S1", "8.4"),
        ("figS2_complexity.png", "Supporting figure S2", "8.8"),
        ("figS3_sfc.png", "Supporting figure S3", "8.7"),
        ("figS4_scheduling.png", "Supporting figure S4", "8.6"),
    ]:
        orig.append([fig, f"`figures/{name}`", sect, "**ORIGINAL**",
                     "produced by `simulations/plot_figures.py` from "
                     f"`simulations/results/`"])
    fig_tab = table(["Figure", "File", "Article section", "Class", "Produced by"], orig)

    num_rows = [
        ["Every value in Sections 3-11 of this file", "**ORIGINAL**",
         "executed by `simulations/run_all.py`, "
         f"{manifest['n_seeds']} seeds, manifest in `simulations/results/run_manifest.json`"],
        ["Scenario parameters marked `[3GPP]` in Table 9", "**REFERENCE-DERIVED**",
         "3GPP TR 36.814 (path loss, shadowing), TS 38.214 Table 5.2.2.1-3 (CQI table), "
         "TS 23.501 Table 5.7.4-1 (5QI packet delay budgets), TR 38.901 (noise figure); "
         "these are *inputs* to the simulation, not results"],
        ["ITU-R M.2410-0 1 ms URLLC radio latency target", "**REFERENCE-DERIVED**",
         "used as a threshold, not measured"],
        ["Attenuated/truncated Shannon bound coefficients (0.88, 0.72)",
         "**REFERENCE-DERIVED**",
         "Mogensen et al., VTC-Spring 2007; used to derive the CQI SNR thresholds"],
        ["EARTH O-RU power-model structure", "**REFERENCE-DERIVED**",
         "Auer et al., IEEE Wireless Communications 2011; the numerical values "
         "(200 W / 20 W / 500 W) are carried over from the previous draft and are model "
         "parameters, not measurements"],
        ["O-RU power values 200 W / 20 W / 500 W", "**ILLUSTRATIVE**",
         "asserted in the previous draft without a source; retained for continuity and "
         "flagged here. If the article keeps them it must say they are assumed values."],
        ["'20-40 % energy reduction in real-world deployments' (Section 9.4)",
         "**REFERENCE-DERIVED**",
         "a literature figure from the previous draft's references [32,33]; it is NOT "
         "reproduced by this package and must be attributed in the same sentence"],
        ["Previous draft's Table 11 scheduling values (85.3 / 142.7 / 128.4 / 131.2 Mbps)",
         "**SUPERSEDED**",
         "replaced by the measured values in Section 6 of this file"],
        ["Previous draft's Table 12 decision times", "**SUPERSEDED**",
         "replaced by the measured values in Section 10 of this file"],
        ["Previous draft's DRL convergence curves", "**SUPERSEDED**",
         "they were tabular proxies; replaced by Section 4 of this file"],
        ["Previous draft's Figure 3 and Figure 4 numbers", "**SUPERSEDED**",
         "no methodology existed; replaced by Sections 8 and 9 of this file"],
        ["Medium-loop controller pre-training", "**ORIGINAL**",
         "trained on the fluid surrogate `MediumSurrogateEnv`, weights and learning "
         "curve in `simulations/results/medium_policy.json`; the surrogate-to-simulator "
         "gap is disclosed in Section 3.8"],
        ["Myopic full-CSI oracle used as the RL normaliser", "**ORIGINAL**",
         "computed by exhaustive search over the joint action space at each step; it is "
         "a myopic upper reference, not an MDP optimum"],
        ["Branch-and-bound times at N >= 200", "**ORIGINAL (lower bound)**",
         f"the search hit the {f(blobs.get('complexity', {}).get('timeout_s', 10), 0)} s "
         "timeout without proving optimality"],
    ]
    num_tab = table(["Item", "Class", "Basis"], num_rows)

    return f"""## PROVENANCE

**Answers Reviewer 1 comment 10.** Every figure and every class of number in the
revised simulation section is classified below as `ORIGINAL` (produced by the code in
`simulations/`), `REFERENCE-DERIVED` (taken from cited literature or a standard) or
`ILLUSTRATIVE` (assumed, with no measurement behind it).

### Figures

{fig_tab}

The following figures of the previous draft are **withdrawn**: the DRL convergence
figure (tabular proxies), the energy-efficiency figure and the RIS figure (no
methodology). Their replacements are listed above. The stale `Fig. 9:` / `Fig. 10:` /
`Fig. 11:` titles baked into the previous images do not appear in any regenerated
figure; titles now live only in the article's caption paragraphs.

### Numbers

{num_tab}

### How to verify any number in this file

```bash
cd simulations
python -m pip install -r requirements.txt
python run_all.py --seeds {manifest['n_seeds']} --out results --workers {manifest['cpu_count']}
python make_report.py --results results --out ../work/sim_results.md
python -m pytest tests -q
```

The raw per-seed values behind every mean and every confidence interval are in
`simulations/results/*.json` and `simulations/results/integrated_per_seed.csv`.

---
"""


def sec_summary(blobs: dict, manifest: dict) -> str:
    integ = blobs.get("integrated")
    learn = blobs.get("learners")
    lines = [
        "| Reviewer comment | Where it is addressed | Status |",
        "|---|---|---|",
        "| R1.1 UMRO-5G not evaluated as an integrated framework | Section 3 (integrated end-to-end runner, five arms, measured loop coupling, Figure 4) | addressed with new original data |",
        "| R1.2 DRL results come from proxy agents | Section 4 (four real agents in NumPy, gradient-checked; proxies deleted) | addressed; non-convergence reported honestly where measured |",
        "| R1.5 statistical analysis mentioned but not presented | Sections 1, 3.6, 4.5, 5.3, 6.1, 8.5, 9.4 (CIs, t and Wilcoxon tests, p-values, Bonferroni and Holm thresholds, effect sizes, power) | addressed |",
        "| R1.6 effective sample size | Section 1.1 (rule stated, enforced in code, unit-tested) | addressed; the 5000-sample claim is deleted |",
        "| R1.8 Figures 3 and 4 have no methodology | Sections 8 and 9 (full models, assumptions, baselines, uncertainty) | addressed |",
        "| R1.9 conclusions stronger than the evidence | Section 12 (claim-by-claim replacement wording) | addressed |",
        "| R1.10 repository contents and provenance separation | `simulations/README.md` and the PROVENANCE section | addressed |",
    ]
    unresolved = [
        "",
        "### Unresolved / flagged",
        "",
        "* The O-RU power values (200 W / 20 W / 500 W) are carried over from the "
        "previous draft with no source. They are classified ILLUSTRATIVE in PROVENANCE. "
        "If a source exists it should be cited; otherwise the article must call them "
        "assumed values.",
        "* The medium-loop controller is pre-trained on a fluid surrogate rather than on "
        "the full simulator, for runtime reasons. This is disclosed in Section 3.8 and "
        "in `simulations/README.md` Section 7.",
        "* The RIS results assume perfect CSI and are upper bounds; no estimation "
        "overhead is modelled.",
        f"* The complexity benchmark uses {manifest['n_seeds_complexity']} seeds "
        f"rather than {manifest['n_seeds']} because it must run sequentially; its "
        f"confidence intervals carry df = {manifest['n_seeds_complexity'] - 1} and this "
        f"is stated wherever those numbers appear.",
    ]
    if learn:
        nc = [a for a, v in learn["converged_fraction"].items() if v < 0.5]
        if nc:
            unresolved.append(
                f"* {', '.join(nc)} did not meet the convergence criteria in the "
                f"majority of runs within the {RLTRAIN.n_episodes}-episode budget. This "
                f"is reported as a negative result, not smoothed over.")
    if integ:
        rows = {(r['arm_a'], r['arm_b'], r['metric']): r for r in integ['family']['rows']}
        ns = [r for r in integ['family']['rows'] if not r['significant_bonferroni']]
        if ns:
            unresolved.append(
                f"* {len(ns)} of the {integ['family']['n_comparisons']} comparisons in "
                f"the integrated end-to-end family are NOT significant after Bonferroni "
                f"correction: "
                + "; ".join(f"{r['metric']} ({SHORT_ARM.get(r['arm_a'], r['arm_a'])} vs "
                            f"{SHORT_ARM.get(r['arm_b'], r['arm_b'])})" for r in ns)
                + ". The article must report these as not significant.")
    return "## SUMMARY\n\n" + "\n".join(lines) + "\n" + "\n".join(unresolved) + "\n"


def main(argv=None) -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--results", default="results")
    ap.add_argument("--out", default="../work/sim_results.md")
    args = ap.parse_args(argv)
    results = Path(args.results)
    manifest = load(results, "run_manifest")
    if manifest is None:
        raise SystemExit(f"no run_manifest.json in {results.resolve()}")

    blobs = {n: load(results, n) for n in
             ("integrated", "learners", "slicing", "scheduling", "sfc", "energy",
              "ris", "complexity")}
    blobs = {k: v for k, v in blobs.items() if v is not None}

    parts = [
        sec_header(manifest),
        sec_statistics(manifest, blobs.get("integrated")),
        sec_scenario_table(),
        sec_integrated(blobs.get("integrated")),
        sec_learners(blobs.get("learners")),
        sec_slicing(blobs.get("slicing")),
        sec_scheduling(blobs.get("scheduling")),
        sec_sfc(blobs.get("sfc")),
        sec_energy(blobs.get("energy")),
        sec_ris(blobs.get("ris")),
        sec_complexity(blobs.get("complexity")),
        sec_consolidated(blobs.get("integrated"), blobs.get("learners"),
                         blobs.get("scheduling"), blobs.get("energy"),
                         blobs.get("ris"), blobs.get("complexity"),
                         blobs.get("sfc")),
        sec_claims(blobs.get("integrated"), blobs.get("learners"),
                   blobs.get("energy"), blobs.get("ris"), blobs.get("complexity")),
        sec_provenance(blobs, manifest),
        sec_summary(blobs, manifest),
    ]
    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(parts), encoding="utf-8")
    print(f"wrote {out.resolve()}  ({len(''.join(parts)):,} characters)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
