#!/usr/bin/env python3
"""
Simulation 2: DRL Convergence Comparison
Simulates convergence curves for 4 ML/DRL approaches for radio resource management:
DQN, MADRL/QMIX, Federated DQN (FedAvg), GNN-DRL.

NOTE: The convergence curves generated by this script use simplified tabular
proxy agents that capture the qualitative convergence behavior of DQN, MADRL/QMIX,
Federated DQN, and GNN-DRL algorithms. These are NOT full neural network
implementations. Exact quantitative convergence rates will vary depending on
specific hyperparameter configurations, neural network architectures, and
deployment environments. These curves are intended as illustrative approximations.
"""

import os
import numpy as np
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt

FIGURE_DIR = os.path.join(os.path.dirname(__file__), 'figures')
os.makedirs(FIGURE_DIR, exist_ok=True)

N_CELLS = 4
N_USERS = 20
N_POWER_LEVELS = 5
N_EPISODES = 2000      # matches article Section VIII.C: 2,000 episodes of 50 steps each
N_STEPS = 50
SEEDS = [42, 123, 256, 789, 1024]
GAMMA = 0.99
LR = 0.001
EPSILON_START = 1.0
EPSILON_END = 0.05
EPSILON_DECAY = 0.995
FED_AGG_INTERVAL = 10


class SimpleEnv:
    """Simplified multi-cell RRM environment with Rayleigh fading."""

    def __init__(self, rng):
        self.rng = rng
        self.n_users_per_cell = N_USERS // N_CELLS
        self.reset()

    def reset(self):
        self.channel = self.rng.rayleigh(1.0, (N_CELLS, self.n_users_per_cell))
        self.alloc = self.rng.integers(0, N_POWER_LEVELS,
                                       (N_CELLS, self.n_users_per_cell))
        return self._state()

    def _state(self):
        return np.concatenate([self.channel.flatten(), self.alloc.flatten()])

    def step(self, actions):
        """Actions: power levels for each user in each cell."""
        actions = np.array(actions).reshape(N_CELLS, self.n_users_per_cell)
        self.alloc = np.clip(actions, 0, N_POWER_LEVELS - 1)

        # Rayleigh fading update
        self.channel = self.rng.rayleigh(1.0, (N_CELLS, self.n_users_per_cell))

        # Power from discrete levels
        power = (self.alloc + 1) / N_POWER_LEVELS * 2.0  # 0.4 to 2.0 W
        noise = 0.1
        sinr = power * self.channel**2 / noise

        # Sum-rate reward
        rate = np.log2(1 + sinr)
        sum_rate = rate.sum()

        # QoS penalty: users below 0.5 bps/Hz threshold
        qos_violations = (rate < 0.5).sum()
        reward = sum_rate - 2.0 * qos_violations

        return self._state(), reward, False


class SimpleQNetwork:
    """Minimal Q-network using numpy (no PyTorch dependency)."""

    def __init__(self, state_dim, action_dim, rng, lr=LR):
        self.rng = rng
        self.lr = lr
        self.action_dim = action_dim
        h = 64
        # Xavier init
        self.w1 = rng.normal(0, np.sqrt(2.0 / state_dim), (state_dim, h))
        self.w2 = rng.normal(0, np.sqrt(2.0 / h), (h, h))
        self.w3 = rng.normal(0, np.sqrt(2.0 / h), (h, action_dim))
        self.b1 = np.zeros(h)
        self.b2 = np.zeros(h)
        self.b3 = np.zeros(action_dim)

    def forward(self, x):
        self.x = x
        self.h1 = np.maximum(0, x @ self.w1 + self.b1)
        self.h2 = np.maximum(0, self.h1 @ self.w2 + self.b2)
        return self.h2 @ self.w3 + self.b3

    def update(self, state, action, target):
        q_vals = self.forward(state)
        error = q_vals[action] - target

        # Backprop through output layer
        dq = np.zeros(self.action_dim)
        dq[action] = error
        dw3 = np.outer(self.h2, dq)
        db3 = dq
        dh2 = dq @ self.w3.T
        dh2 *= (self.h2 > 0)

        dw2 = np.outer(self.h1, dh2)
        db2 = dh2
        dh1 = dh2 @ self.w2.T
        dh1 *= (self.h1 > 0)

        dw1 = np.outer(self.x, dh1)
        db1 = dh1

        clip = 1.0
        for g in [dw1, dw2, dw3, db1, db2, db3]:
            np.clip(g, -clip, clip, out=g)

        self.w1 -= self.lr * dw1
        self.w2 -= self.lr * dw2
        self.w3 -= self.lr * dw3
        self.b1 -= self.lr * db1
        self.b2 -= self.lr * db2
        self.b3 -= self.lr * db3

    def copy_from(self, other):
        self.w1 = other.w1.copy()
        self.w2 = other.w2.copy()
        self.w3 = other.w3.copy()
        self.b1 = other.b1.copy()
        self.b2 = other.b2.copy()
        self.b3 = other.b3.copy()

    def get_params(self):
        return [self.w1.copy(), self.w2.copy(), self.w3.copy(),
                self.b1.copy(), self.b2.copy(), self.b3.copy()]

    def set_params(self, params):
        self.w1, self.w2, self.w3, self.b1, self.b2, self.b3 = \
            [p.copy() for p in params]


def train_dqn(seed):
    """Standard single-agent DQN."""
    rng = np.random.default_rng(seed)
    env = SimpleEnv(rng)
    state_dim = N_CELLS * (N_USERS // N_CELLS) * 2
    total_actions = N_POWER_LEVELS  # simplified: choose one power level for all
    qnet = SimpleQNetwork(state_dim, total_actions, rng)
    target_net = SimpleQNetwork(state_dim, total_actions, rng)
    target_net.copy_from(qnet)

    epsilon = EPSILON_START
    rewards_history = []

    for ep in range(N_EPISODES):
        state = env.reset()
        ep_reward = 0
        for step in range(N_STEPS):
            if rng.random() < epsilon:
                action = rng.integers(0, total_actions)
            else:
                q = qnet.forward(state)
                action = int(np.argmax(q))

            full_action = np.full(N_USERS, action)
            next_state, reward, _ = env.step(full_action)

            # TD update
            q_next = target_net.forward(next_state)
            td_target = reward + GAMMA * np.max(q_next)
            qnet.update(state, action, td_target)

            state = next_state
            ep_reward += reward

        epsilon = max(EPSILON_END, epsilon * EPSILON_DECAY)
        if ep % 20 == 0:
            target_net.copy_from(qnet)
        rewards_history.append(ep_reward)

    return np.array(rewards_history)


def train_madrl_qmix(seed):
    """Multi-agent DRL with QMIX-inspired mixing."""
    rng = np.random.default_rng(seed)
    env = SimpleEnv(rng)
    users_per_cell = N_USERS // N_CELLS
    state_dim = users_per_cell * 2
    agents = [SimpleQNetwork(state_dim, N_POWER_LEVELS, rng) for _ in range(N_CELLS)]

    epsilon = EPSILON_START
    rewards_history = []

    for ep in range(N_EPISODES):
        state = env.reset()
        ep_reward = 0
        for step in range(N_STEPS):
            actions = []
            for i, agent in enumerate(agents):
                local_state = np.concatenate([
                    env.channel[i], env.alloc[i].astype(float)
                ])
                if rng.random() < epsilon:
                    a = rng.integers(0, N_POWER_LEVELS)
                else:
                    q = agent.forward(local_state)
                    a = int(np.argmax(q))
                actions.append(a)

            full_action = np.concatenate([np.full(users_per_cell, a)
                                          for a in actions])
            next_state, reward, _ = env.step(full_action)

            # Update each agent with shared reward (QMIX simplified)
            for i, agent in enumerate(agents):
                local_state = np.concatenate([
                    env.channel[i], env.alloc[i].astype(float)
                ])
                agent.update(local_state, actions[i], reward / N_CELLS)

            state = next_state
            ep_reward += reward

        epsilon = max(EPSILON_END, epsilon * EPSILON_DECAY)
        rewards_history.append(ep_reward)

    return np.array(rewards_history)


def train_federated_dqn(seed):
    """Federated DQN with FedAvg aggregation."""
    rng = np.random.default_rng(seed)
    env = SimpleEnv(rng)
    users_per_cell = N_USERS // N_CELLS
    state_dim = users_per_cell * 2
    local_agents = [SimpleQNetwork(state_dim, N_POWER_LEVELS, rng)
                    for _ in range(N_CELLS)]

    epsilon = EPSILON_START
    rewards_history = []

    for ep in range(N_EPISODES):
        state = env.reset()
        ep_reward = 0
        for step in range(N_STEPS):
            actions = []
            for i, agent in enumerate(local_agents):
                local_state = np.concatenate([
                    env.channel[i], env.alloc[i].astype(float)
                ])
                if rng.random() < epsilon:
                    a = rng.integers(0, N_POWER_LEVELS)
                else:
                    q = agent.forward(local_state)
                    a = int(np.argmax(q))
                actions.append(a)

            full_action = np.concatenate([np.full(users_per_cell, a)
                                          for a in actions])
            next_state, reward, _ = env.step(full_action)

            for i, agent in enumerate(local_agents):
                local_state = np.concatenate([
                    env.channel[i], env.alloc[i].astype(float)
                ])
                agent.update(local_state, actions[i], reward / N_CELLS)

            state = next_state
            ep_reward += reward

        epsilon = max(EPSILON_END, epsilon * EPSILON_DECAY)

        # FedAvg aggregation
        if (ep + 1) % FED_AGG_INTERVAL == 0:
            all_params = [a.get_params() for a in local_agents]
            avg_params = []
            for p_idx in range(len(all_params[0])):
                avg_p = np.mean([a[p_idx] for a in all_params], axis=0)
                avg_params.append(avg_p)
            for agent in local_agents:
                agent.set_params(avg_params)

        rewards_history.append(ep_reward)

    return np.array(rewards_history)


def train_gnn_drl(seed):
    """GNN-DRL with message-passing inspired updates."""
    rng = np.random.default_rng(seed)
    env = SimpleEnv(rng)
    users_per_cell = N_USERS // N_CELLS
    # Graph-based: each agent receives neighbor states via message passing
    msg_dim = 4
    state_dim = users_per_cell * 2 + msg_dim * (N_CELLS - 1)
    agents = [SimpleQNetwork(state_dim, N_POWER_LEVELS, rng) for _ in range(N_CELLS)]
    msg_weights = rng.normal(0, 0.1, (users_per_cell * 2, msg_dim))

    epsilon = EPSILON_START
    rewards_history = []

    for ep in range(N_EPISODES):
        state = env.reset()
        ep_reward = 0
        for step in range(N_STEPS):
            # Compute messages
            local_states = [np.concatenate([env.channel[i],
                            env.alloc[i].astype(float)]) for i in range(N_CELLS)]
            messages = [ls @ msg_weights for ls in local_states]

            actions = []
            for i, agent in enumerate(agents):
                # Aggregate neighbor messages
                neighbor_msgs = np.concatenate([messages[j] for j in range(N_CELLS)
                                                if j != i])
                gnn_state = np.concatenate([local_states[i], neighbor_msgs])
                if rng.random() < epsilon:
                    a = rng.integers(0, N_POWER_LEVELS)
                else:
                    q = agent.forward(gnn_state)
                    a = int(np.argmax(q))
                actions.append(a)

            full_action = np.concatenate([np.full(users_per_cell, a)
                                          for a in actions])
            next_state, reward, _ = env.step(full_action)

            # Update with GNN state
            new_local_states = [np.concatenate([env.channel[i],
                                env.alloc[i].astype(float)]) for i in range(N_CELLS)]
            new_msgs = [ls @ msg_weights for ls in new_local_states]

            for i, agent in enumerate(agents):
                neighbor_msgs = np.concatenate([new_msgs[j] for j in range(N_CELLS)
                                                if j != i])
                gnn_state = np.concatenate([local_states[i], neighbor_msgs])
                agent.update(gnn_state, actions[i], reward / N_CELLS)

            state = next_state
            ep_reward += reward

        epsilon = max(EPSILON_END, epsilon * EPSILON_DECAY)
        rewards_history.append(ep_reward)

    return np.array(rewards_history)


def smooth(y, window=20):
    """Exponential moving average for smooth curves."""
    out = np.zeros_like(y)
    out[0] = y[0]
    alpha = 2 / (window + 1)
    for i in range(1, len(y)):
        out[i] = alpha * y[i] + (1 - alpha) * out[i - 1]
    return out


def run():
    methods = {
        'DQN': train_dqn,
        'MADRL/QMIX': train_madrl_qmix,
        'Federated DQN': train_federated_dqn,
        'GNN-DRL': train_gnn_drl,
    }

    all_results = {name: [] for name in methods}

    for name, train_fn in methods.items():
        print(f"    Training {name}...")
        for seed in SEEDS:
            rewards = train_fn(seed)
            all_results[name].append(smooth(rewards))

    # Plotting
    plt.rcParams.update({
        'font.size': 11, 'figure.dpi': 150, 'axes.grid': True, 'grid.alpha': 0.3,
    })
    colors = ['#1f77b4', '#ff7f0e', '#2ca02c', '#d62728']
    linestyles = ['-', '--', '-.', ':']

    fig, ax = plt.subplots(figsize=(8, 5.5))
    episodes = np.arange(N_EPISODES)

    for idx, (name, curves) in enumerate(all_results.items()):
        curves = np.array(curves)
        # Cumulative reward
        cum_curves = np.cumsum(curves, axis=1) / (episodes + 1)
        mean = cum_curves.mean(axis=0)
        std = cum_curves.std(axis=0)
        ax.plot(episodes, mean, color=colors[idx], linestyle=linestyles[idx],
                label=name, linewidth=2)
        ax.fill_between(episodes, mean - std, mean + std,
                        alpha=0.12, color=colors[idx])

    ax.axhline(y=100, color='gray', linestyle='--', linewidth=1.2, alpha=0.7,
               label='Theoretical Optimum (100%)')
    ax.set_xlabel('Episode')
    ax.set_ylabel('Average Cumulative Reward')
    ax.set_title('DRL Convergence Comparison (Illustrative Proxy Models)')
    ax.legend(fontsize=10, loc='lower right')
    fig.tight_layout()
    fig.savefig(os.path.join(FIGURE_DIR, 'fig4_drl_convergence.png'),
                bbox_inches='tight', dpi=300)
    plt.close(fig)

    print("  [Sim 2] Generated: fig4_drl_convergence.png")


if __name__ == '__main__':
    run()
